{
  "hash": "62200fe5177ca94e460414a5ca8b899f",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"When Velocity Matters: A Contingent Capacity Framework for Disaster Recovery Administration\"\nformat:\n  html:\n    toc: true\n  pdf:\n    toc: false\n  docx:\n    toc: false\n---\n\n\n## Abstract {.unnumbered}\n\nAdministrative capacity effects on program outcomes are typically assumed to be universal. Analysis of 152 CDBG-DR grantee-disaster pairs reveals that spending velocity---the quarterly rate of fund expenditure---predicts recovery completion in highly context-dependent ways. Meta-analysis of 16 velocity effect estimates shows a median hazard ratio of 4.60, but effects range from null (housing programs, HR=0.82) to extreme (wildfire disasters, HR=51.09). Velocity effects concentrate in contexts where time constraints bind and capacity substitutes are absent: wildfire disasters requiring completion before next fire season (HR=51.09), administration programs lacking fixed construction timelines (HR=30.74), late program phases facing closeout deadlines (HR=5.00), and novice grantees without institutional alternatives (HR=4.61). These findings support a contingent capacity framework: administrative capacity is not universally beneficial but depends on disaster urgency, program type, lifecycle phase, and organizational experience. Policy implications favor targeted interventions in high-leverage contexts over universal capacity-building.\n\n## Evidence for Practice {.unnumbered}\n\n- **Prioritize wildfire programs**: Spending velocity has 10x stronger effects on wildfire recovery (HR=51.09) than hurricanes (HR=4.58), justifying intensive technical assistance for fire-affected communities\n- **Focus on administration programs**: Velocity most strongly predicts completion for planning and capacity-building activities (HR=30.74), not physical construction\n- **Invest in late-phase support**: Late-stage velocity (HR=5.00) matters more than early planning velocity (HR=2.04), suggesting closeout assistance deserves priority\n- **Target novice grantees**: First-time CDBG-DR recipients depend more on velocity (HR=4.61) than experienced grantees (HR=3.15), who have institutional alternatives\n- **Implement differentiated monitoring**: Allocate 60% of technical assistance to high-leverage contexts (wildfire, administration, novice) rather than uniform monitoring\n\n# Introduction\n\nFederal disaster recovery programs face persistent completion challenges. The Community Development Block Grant-Disaster Recovery (CDBG-DR) program, which has distributed over $90 billion since 1993, exhibits substantial variation in completion timing, with some programs achieving 95% expenditure within five years while others remain incomplete after two decades [@gao2019; @hudoig2021]. Understanding what administrative factors accelerate recovery completion remains a central question for disaster policy.\n\nAdministrative capacity---the ability of government organizations to effectively implement policy---has emerged as a key explanatory factor [@wu2015; @christensen2017]. Prior research identifies multiple capacity dimensions including human capital, organizational resources, and management practices [@ingraham2007; @painter2002]. In disaster contexts, financial management capacity---particularly the ability to rapidly obligate, disburse, and expend recovery funds---appears especially consequential [@gerber2022; @smith2021].\n\nHowever, existing research typically treats capacity effects as universal: more capacity is assumed to improve outcomes regardless of context. This assumption may obscure important heterogeneity. If capacity effects vary by disaster type, program characteristics, or organizational experience, uniform capacity-building interventions may be poorly targeted.\n\nThis analysis investigates spending velocity---the quarterly rate at which grantees expend CDBG-DR funds---as an operational capacity measure. Three research questions guide the investigation: (1) When during the program lifecycle does velocity matter most? (2) Where across disaster and program types are velocity effects strongest? (3) Why do velocity effects vary, and what mechanisms explain observed heterogeneity?\n\nFindings support a contingent capacity framework. Velocity effects are not universal but concentrate in contexts where two conditions hold: time constraints bind (limiting the value of slow, steady progress) and capacity substitutes are absent (preventing alternative pathways to completion). Wildfire disasters, administration programs, late program phases, and novice grantees exhibit the strongest velocity effects because they combine time pressure with limited alternatives.\n\nThe theoretical contribution lies in demonstrating that administrative capacity effects are contingent on context. Rather than assuming linear, universal benefits, public administration research should identify boundary conditions and moderators that determine when capacity investments yield returns. The policy contribution is equally direct: velocity-enhancing interventions should concentrate on high-leverage contexts---wildfire recovery, administrative programs, closeout phases, and first-time grantees---rather than applying uniform capacity-building across all disaster recovery programs.\n\n# Literature Review\n\n## Recovery as a Multi-Sector Governance Process\n\nDisaster recovery represents a prolonged, multi-dimensional governance process---not a discrete \"rebuilding\" phase. Foundational disaster scholarship emphasizes that recovery includes re-establishing housing, livelihoods, public services, and social networks while institutions are disrupted and priorities are contested [@quarantelli1999]. Planning and disaster research further underscores that recovery decision-making is \"time-compressed\": urgent actions (temporary shelter, debris removal, safety repairs) occur alongside long-horizon choices about land use, infrastructure systems, and redevelopment, often before damages and needs are fully known [@olshansky2012; @zhang2019]. International policy frameworks reinforce this governance lens by defining recovery as a moment to reduce future risk and \"build back better,\" requiring coordination across sectors and levels of government [@unisdr2015].\n\nFrom a comparative standpoint, recovery governance is interdependent: national governments, subnational authorities, private contractors, civil society organizations, and international donors frequently control different resources and approvals, producing long decision chains and multiple accountability relationships. Post-disaster needs assessments and recovery strategies are intended to create a shared evidence base, align priorities, and coordinate financing across actors [@gfdrr2013]. Yet this model also highlights a persistent tension: recovery systems must accelerate action while maintaining fiduciary controls, transparency, and legitimacy, all of which can slow implementation.\n\n## Financing Long-Term Recovery\n\nLong-term recovery is typically financed through layered streams (insurance, loans, philanthropic funding, and public transfers) that arrive at different speeds and operate under different rules. Where governments rely on discretionary recovery funds---block grants, special reconstruction funds, or donor-financed recovery packages---program design often trades flexibility for intensified reporting, procurement, and compliance requirements intended to safeguard public resources and target assistance. In the U.S. context, this tradeoff is particularly visible in the Community Development Block Grant--Disaster Recovery (CDBG-DR) mechanism: supplemental appropriations administered through HUD's CDBG authorities are repeatedly created to meet unmet recovery needs, but each appropriation can arrive with distinct statutory directions and implementing requirements, complicating program design and startup [@jaroscak2020].\n\nBecause CDBG-DR is structured as a flexible block grant, grantees have broad discretion to tailor activities to local needs; at the same time, discretion is paired with extensive planning, documentation, and monitoring expectations. Oversight bodies consistently describe performance challenges that follow from this design, including long delays between allocation, program launch, and closeout---often linked to procurement, environmental review, and the establishment of administrative systems capable of handling eligibility determinations, construction management, and payments [@gao2019; @hud2020].\n\n## Capacity and Implementation\n\nA central claim across disaster recovery and public administration research is that capacity shapes both the speed and distribution of recovery. Capacity is multidimensional. In public policy scholarship, \"policy capacity\" is frequently defined as a bundle of analytical, operational, and political competences and capabilities at individual, organizational, and system levels [@wu2015]. This framework maps well to recovery: governments must (1) produce credible needs assessments and priorities (analytical), (2) translate plans into contracts, reimbursements, and completed projects through procurement and financial systems (operational), and (3) sustain legitimacy and coalitional support under high stress and conflict over redevelopment choices (political).\n\nDisaster-focused research aligns with this view by showing that institutional arrangements and administrative resources (staffing, expertise, and organizational experience) are associated with resilience and recovery performance [@gerber2022]. Recovery also depends on intergovernmental and cross-sector networks, where coordination and information sharing can substitute for hierarchical authority but require deliberate relationship management and trust-building [@kapucu2009; @waugh2006].\n\nBeyond disaster-specific literature, intergovernmental grants research provides a complementary lens: administrative capacity influences not only whether jurisdictions secure grants, but whether they can absorb them---converting awards into implemented projects and spent funds. Research links political and administrative capacity to federal grant flows into local areas [@hall2008] and shows that administrative capacity can shape the pace of utilizing awarded funds during time-bounded program rollouts [@shybalkina2024]. Related evidence from high-stakes, time-sensitive federal programs indicates that implementation timing depends on both the clarity of federal guidance and the recipient's administrative capacity to stand up processes, contract quickly, and manage compliance [@carley2015; @terman2015].\n\n## Contingency Theory and Context-Dependent Capacity Effects\n\nDespite extensive research linking capacity to recovery outcomes, existing work typically treats capacity effects as universal: more capacity is assumed to improve outcomes regardless of context. Classical contingency theory challenges this assumption, arguing that organizational effectiveness depends on alignment between organizational characteristics and environmental conditions [@donaldson2001; @burns1961]. Mechanistic structures suit stable environments while organic structures suit dynamic environments [@lawrence1967]. The theory implies that \"best practices\" are contextual: what works in one environment may fail in another.\n\nApplied to administrative capacity, contingency theory suggests that capacity effects should vary by task characteristics. Simple, repetitive tasks may benefit less from additional capacity than complex, uncertain tasks [@galbraith1973]. Similarly, capacity investments may yield higher returns when time constraints create urgency than when extended timelines permit slower progress. This contingent perspective implies that capacity effects should depend on: (1) task complexity and uncertainty, (2) time constraints and urgency, (3) availability of substitute resources, and (4) lifecycle phase and organizational learning.\n\nOrganizational learning theory provides additional nuance. Repeated exposure to similar tasks should improve performance [@argote2011; @levitt1988]. Experienced grantees may have developed institutional knowledge, established vendor relationships, and accumulated political capital that substitute for other capacity dimensions. Novice grantees, lacking these alternatives, may depend more heavily on operational throughput measures like spending velocity.\n\n## Mechanisms That Delay or Accelerate Recovery\n\nHousing recovery programs often sit at the intersection of intense public pressure, stringent compliance regimes, and disrupted supply chains. Planning research identifies recurring bottlenecks: procurement and contracting rules, permitting and environmental review requirements, contractor scarcity, and administrative constraints embedded in program design [@smith2021; @zhang2019]. These constraints are especially salient for complex activities (multifamily development, major rehabilitation) that require multiple rounds of approvals, layered financing, and specialized technical capacity.\n\nProgram-level evidence also underscores how strongly startup capacity influences downstream disbursement and completion. A large review of CDBG-DR housing activities finds substantial delays between disasters and the point at which housing activities begin distributing funds, with wide variation across disasters and program types [@hudpdr2021]. Oversight work similarly flags program startup as a critical bottleneck and highlights that progress reporting can be difficult to interpret for oversight and transparency, limiting the ability to detect \"stuck\" milestones and intervene [@gao2022].\n\nDisaster characteristics also shape recovery trajectories in systematic ways. Hurricane recovery unfolds over years as communities rebuild housing and infrastructure [@peacock2022]. Wildfire recovery faces different constraints: seasonal fire risk creates urgency to complete rebuilding before the next fire season, and destroyed structures often cannot be rebuilt in identical locations due to updated fire codes [@mockrin2015; @kramer2019].\n\n## Equity and the Consequences of Delay\n\nRecovery speed is not merely a technical performance metric; it has distributional consequences. Delays can lengthen displacement, increase out-of-pocket costs, and widen gaps between households with access to insurance or credit and those reliant on public assistance. Empirical work shows that post-disaster spending patterns can exacerbate inequality, with disadvantaged communities often facing greater barriers and delayed access to recovery resources [@howell2019]. Research on disaster housing assistance similarly finds evidence of inequitable recovery outcomes across programs and populations, raising concerns that administrative processes and eligibility rules can translate into unequal benefits and uneven timelines [@peacock2022]. Broader analyses of recovery funding distribution further highlight persistent inequities relative to vulnerability, reinforcing that administrative choices---allocation formulas, documentation requirements, and program design---shape who benefits and how quickly [@emrich2020].\n\n## Measuring Recovery Pace with Duration Models\n\nDespite a large qualitative and case-based literature on recovery governance, empirically measuring recovery \"pace\" remains difficult. Many studies rely on audits, descriptive dashboards, or case studies that illuminate mechanisms but limit comparative generalization [@smith2021; @gao2019]. Quantitative analyses often use cross-sectional or panel regressions to relate recovery outcomes to capacity, hazard severity, or socioeconomic conditions, but these approaches can implicitly exclude incomplete programs---precisely the cases most informative about delay dynamics.\n\nDuration models provide a strong methodological fit because they explicitly model time to reach milestones (substantial expenditure, project completion) and can incorporate right-censored observations (programs not complete at the time of analysis). Event history and survival analysis are well established in the social sciences for studying policy adoption, implementation timing, and institutional change [@boxsteffensmeier2004]. Applying these methods to disaster recovery finance helps address a core inferential problem in recovery research: many programs remain active for years, so excluding ongoing cases can bias estimates and reduce external validity.\n\nThis methodological and conceptual landscape points to an important empirical agenda: operationalizing capacity as implementation throughput (spending velocity), testing whether velocity effects vary systematically across contexts, and linking those measures to the timing of recovery spending milestones using methods designed for time-to-event data.\n\n# Data and Methods\n\n## The CDBG-DR Program\n\nThe Community Development Block Grant-Disaster Recovery (CDBG-DR) program represents the primary federal mechanism for long-term disaster recovery funding in the United States. Administered by the Department of Housing and Urban Development (HUD), CDBG-DR provides flexible block grants to state and local governments following presidentially-declared disasters. Unlike immediate emergency response programs such as FEMA Public Assistance, CDBG-DR funds address unmet recovery needs that emerge after insurance payments and other federal assistance have been exhausted, typically focusing on housing rehabilitation, infrastructure repair, and economic revitalization [@hudpdr2021].\n\nThe program operates through a multi-stage financial pipeline. Congress appropriates disaster-specific funding, HUD allocates funds to eligible grantees based on damage assessments, grantees develop action plans detailing intended activities, HUD approves plans and obligates funds, grantees draw down (disburse) funds as projects progress, and grantees expend funds on eligible activities. Each stage creates potential delays, and the pace at which funds move through this pipeline—particularly from disbursement to final expenditure—reflects organizational capacity to manage complex recovery programs [@jaroscak2020].\n\nGrantees must submit Quarterly Performance Reports (QPRs) to HUD documenting financial progress and activity status. These standardized reports provide the foundation for systematic analysis of recovery implementation timing across disasters and jurisdictions.\n\n## Sample and Data Sources\n\nAnalysis draws on CDBG-DR Quarterly Performance Report data spanning 2003-2023, representing two decades of disaster recovery administration. The dataset contains 130,605 quarterly observations across 152 grantee-disaster pairs from 78 unique jurisdictions. This sample includes all CDBG-DR allocations with sufficient reporting history to construct velocity measures and assess completion status.\n\nThe sample reflects the diversity of CDBG-DR administration. Government type is roughly balanced: 37 state governments (47%) and 40 local governments (53%) serve as grantees. State governments typically manage larger allocations and coordinate recovery across multiple jurisdictions, while local governments administer programs focused on their own communities. Prior research suggests these administrative contexts create different capacity dynamics [@carley2015; @terman2015].\n\n@tbl-descriptives presents descriptive statistics for key sample characteristics, and @fig-sample-composition visualizes the distribution across disaster types, program types, and government levels.\n\n::: {#tbl-descriptives .cell tbl-cap='Sample Descriptive Statistics' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Characteristic              | Value       |\n|:----------------------------|:------------|\n| **Sample Size**             |             |\n| Grantee-disaster pairs      | 152         |\n| Unique jurisdictions        | 78          |\n| Quarterly observations      | 130,605     |\n| **Government Type**         |             |\n| State governments           | 37 (48%)    |\n| Local governments           | 40 (52%)    |\n| **Disaster Type**           |             |\n| Hurricane                   | 77 (51%)    |\n| Wildfire/Fire               | 27 (18%)    |\n| Other (flood, storms)       | 48 (32%)    |\n| **Primary Program Type**    |             |\n| Housing                     | 50 (33%)    |\n| Infrastructure              | 56 (37%)    |\n| Administration              | 34 (22%)    |\n| Other                       | 12 (8%)     |\n| **Completion Status (95%)** |             |\n| Complete                    | 41 (27.0%)  |\n| Right-censored (ongoing)    | 111 (73.0%) |\n| **Velocity (pp/quarter)**   |             |\n| Mean                        | 1.78        |\n| Median                      | 0.87        |\n| Standard deviation          | 22.6        |\n:::\n:::\n\n\n::: {#cell-fig-sample-composition .cell fig-height='4' fig-width='10' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Sample Composition by Disaster Type, Program Type, and Government Level](index_files/figure-html/fig-sample-composition-output-1.png){#fig-sample-composition width=950 height=373}\n:::\n:::\n\n\n## Disaster and Program Characteristics\n\nThe sample encompasses 18 distinct disaster events spanning multiple hazard types and eras. Hurricanes dominate, reflecting the frequency and severity of Atlantic tropical cyclones: 77 grantee-disaster pairs (51%) involve hurricane recovery, including major events such as Hurricanes Katrina (2005), Sandy (2012), Harvey, Irma, and Maria (2017). Wildfire recovery accounts for 27 pairs (18%), concentrated in Western states and increasing in recent years. The remaining 48 pairs (32%) involve floods, severe storms, and multi-hazard events.\n\nThree temporal eras structure the data. The pre-2010 period (6 pairs) includes early program implementation following Hurricanes Katrina and Rita. The 2010-2020 period (126 pairs) represents the core analytical sample, encompassing Hurricane Sandy recovery and the evolution of HUD oversight practices. The post-2020 period (11 pairs) includes recent disasters with limited follow-up time. @fig-disaster-timeline visualizes the distribution of major disaster events across the sample period.\n\n::: {#cell-fig-disaster-timeline .cell fig-height='5' fig-width='11' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Timeline of Major Disaster Events in Sample (2003-2023)](index_files/figure-html/fig-disaster-timeline-output-1.png){#fig-disaster-timeline width=1035 height=467}\n:::\n:::\n\n\nProgram composition varies across grantees. Housing reconstruction and rehabilitation dominates many programs (50 pairs, 33%), requiring coordination with individual homeowners and navigating complex beneficiary eligibility rules. Infrastructure repair programs (56 pairs, 37%) involve procurement, environmental review, and construction management. Administration-focused allocations (34 pairs, 22%) support planning, capacity building, and program management activities.\n\n## Outcome Variable and Censoring\n\nProgram completion is defined as achieving 95% of cumulative grant expenditure—the point at which nearly all allocated funds have been spent and the recovery program approaches closeout. This threshold balances program maturity (substantial implementation complete) against analytical tractability (sufficient completed cases for estimation).\n\nAt the 95% threshold, only 41 programs (26.3%) have reached completion. The remaining 111 programs (73.7%) remain ongoing and are right-censored at their last observed quarter. High censoring rates are common in long-term recovery programs: CDBG-DR grants routinely span 10-15 years from allocation to closeout [@gao2022]. Among completed programs, median time to 95% completion is 68 quarters (17 years), with substantial variation (range: 12-120+ quarters).\n\nThe extensive right-censoring necessitates survival analysis methods. Standard regression approaches would either exclude 73.7% of observations (introducing severe selection bias) or treat ongoing programs as \"not completed\" (mischaracterizing programs that will eventually complete). Survival analysis properly incorporates censored observations, using all available follow-up time while accounting for the unknown completion timing of ongoing programs. @fig-completion-status illustrates the completion rates across different expenditure thresholds.\n\n::: {#cell-fig-completion-status .cell fig-height='4' fig-width='10' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Program Completion Status and Threshold Sensitivity](index_files/figure-html/fig-completion-status-output-1.png){#fig-completion-status width=908 height=373}\n:::\n:::\n\n\n## Spending Velocity Operationalization\n\nSpending velocity captures the quarterly rate of fund expenditure as a proportion of total grant obligations. Calculation uses standardized ratios with fixed denominators to avoid computational artifacts:\n\n$$\\text{Velocity}_t = \\frac{\\text{Expended}_t}{\\text{Obligated}_{\\text{final}}} - \\frac{\\text{Expended}_{t-1}}{\\text{Obligated}_{\\text{final}}}$$\n\nThis specification uses the final obligated amount as a stable denominator across all quarters, ensuring that velocity changes reflect actual spending acceleration or deceleration rather than administrative adjustments to obligation levels. Values are winsorized at the 1st and 99th percentiles to limit outlier influence. Mean quarterly velocity is 1.78 percentage points, with substantial variation (SD = 22.6 pp) reflecting the episodic nature of large expenditure events. @fig-velocity-distribution shows the distribution of quarterly velocity values.\n\n::: {#cell-fig-velocity-distribution .cell fig-height='5' fig-width='8' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Distribution of Quarterly Spending Velocity](index_files/figure-html/fig-velocity-distribution-output-1.png){#fig-velocity-distribution width=758 height=470}\n:::\n:::\n\n\nPhase-specific velocity measures capture temporal dynamics. Programs are divided into terciles based on elapsed time: early phase (first third), middle phase (second third), and late phase (final third). Mean velocity within each phase creates early, middle, and late velocity measures enabling investigation of lifecycle effects—whether velocity matters more during program startup, steady-state implementation, or closeout.\n\n## Analytical Strategy\n\nThe primary method is Cox proportional hazards regression with time to 95% completion as the outcome. The basic model estimates:\n\n$$h(t) = h_0(t) \\exp(\\beta_1 \\text{Velocity} + \\mathbf{X}\\boldsymbol{\\gamma})$$\n\nwhere $h(t)$ is the hazard of completion at time $t$, $h_0(t)$ is the baseline hazard, and $\\mathbf{X}$ includes control variables for disaster era and grant size. Hazard ratios greater than 1.0 indicate that higher velocity is associated with faster completion (increased hazard of reaching the 95% threshold).\n\nContext-specific effects are estimated through stratified Cox models. Separate models by disaster type (hurricane, wildfire, flood, other), program type (housing, infrastructure, administration), and grantee experience (novice vs. experienced) test whether velocity effects vary systematically across implementation contexts. Formal interaction tests assess whether stratified differences exceed sampling variability.\n\nTrajectory clustering uses K-means on quarterly velocity profiles to identify distinct velocity patterns. Clusters are characterized by mean velocity, velocity variance, and completion outcomes. Kaplan-Meier survival curves by cluster visualize how trajectory patterns relate to completion timing.\n\nMeta-analysis aggregates velocity effect estimates across all stratified models. The median hazard ratio summarizes the central tendency of velocity effects, while the range and interquartile interval characterize heterogeneity. Forest plots visualize effect estimates with 95% confidence intervals, enabling visual assessment of which contexts show the strongest velocity-completion relationships.\n\n# Results\n\n## Overall Velocity Effect\n\n::: {#tbl-overall .cell tbl-cap='Overall Velocity Effect on Program Completion' execution_count=7}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Metric       |   Value |\n|:-------------|--------:|\n| Hazard Ratio |   4.44  |\n| 95% CI Lower |   1.39  |\n| 95% CI Upper |  14.17  |\n| p-value      |   0.012 |\n:::\n:::\n\n\nSpending velocity significantly predicts program completion (HR=4.44, 95% CI: 1.39-14.17, p=0.012). A one percentage point increase in quarterly expenditure velocity is associated with a 4.44-fold increase in the hazard of reaching 95% completion, controlling for disaster era and grant size.\n\nThis overall effect, while statistically significant, obscures substantial heterogeneity across contexts. The following sections decompose velocity effects by temporal phase, organizational experience, program type, and disaster context.\n\n## Temporal Dynamics\n\n::: {#tbl-phase .cell tbl-cap='Phase-Specific Velocity Effects' execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Model               |   N |   N_Events |   Early_Velocity_HR |   Early_Velocity_p |   Mid_Velocity_HR |   Mid_Velocity_p |   Late_Velocity_HR |   Late_Velocity_p |\n|:--------------------|----:|-----------:|--------------------:|-------------------:|------------------:|-----------------:|-------------------:|------------------:|\n| Overall_Velocity    | 143 |        106 |           nan       |       nan          |        nan        |       nan        |          nan       |       nan         |\n| Early_Velocity_Only | 138 |        106 |             2.50944 |         0.00816754 |        nan        |       nan        |          nan       |       nan         |\n| Three_Phase         | 138 |        106 |             2.03721 |         0.157198   |          0.369084 |         0.183944 |            5.00148 |         0.0396985 |\n| Acceleration        | 138 |        106 |           nan       |       nan          |        nan        |       nan        |          nan       |       nan         |\n:::\n:::\n\n\nLate-phase velocity dominates completion prediction. When all three phase velocities are included simultaneously, only late-phase velocity remains significant (HR=5.00, 95% CI: 1.07-23.31, p=0.040). Early-phase velocity shows a positive but non-significant effect (HR=2.04, p=0.157), while mid-phase velocity is non-significant and negative (HR=0.37, p=0.184).\n\nThis pattern suggests that closeout bottlenecks---compliance verification, final reporting, and fund reconciliation---represent critical barriers to completion. Programs that maintain high velocity through these late-stage hurdles complete faster, while programs that slow in the final phase experience substantial delays.\n\nTrajectory clustering reinforces this interpretation. K-means clustering on quarterly velocity profiles identifies three patterns: Fast-Consistent (11% of programs), Moderate (88%), and Slow-Start (1%). Fast-Consistent programs maintain high velocity throughout and complete in a median of 45 quarters. Moderate programs complete in 68 quarters---a difference of 23 quarters (5.75 years). The small Slow-Start cluster lacks sufficient observations for reliable completion estimates.\n\n## Experience Moderation\n\n::: {#tbl-experience .cell tbl-cap='Velocity Effects by Grantee Experience' execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Experience   |   HR |   p-value |\n|:-------------|-----:|----------:|\n| Novice       | 4.61 |     0.043 |\n| Experienced  | 3.15 |     0.237 |\n:::\n:::\n\n\nVelocity effects are stronger for novice grantees (HR=4.61, p=0.043) than experienced grantees (HR=3.15, p=0.237). First-time CDBG-DR recipients show significant velocity-completion associations, while organizations with prior CDBG-DR experience show weaker, non-significant effects.\n\nThis pattern is consistent with capacity substitution. Experienced grantees have developed institutional knowledge, vendor relationships, and political capital through prior disaster recovery work. These accumulated resources provide alternative pathways to completion that substitute for spending velocity. Novice grantees, lacking these alternatives, depend more heavily on velocity as their primary completion mechanism.\n\nNotably, analysis finds no evidence of learning curves across successive disasters. Among grantees managing multiple CDBG-DR grants, velocity does not systematically improve from first to subsequent grants (r=0.175, p=0.075). This null finding suggests that disaster heterogeneity and staff turnover may prevent direct knowledge transfer across recovery episodes.\n\n## Program Type Heterogeneity\n\n::: {#cell-fig-program-type .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Velocity Effects by Program Type](index_files/figure-html/fig-program-type-output-1.png){#fig-program-type width=600}\n:::\n:::\n\n\nProgram type substantially moderates velocity effects. Administration programs show extreme velocity effects (HR=30.74, 95% CI: 3.12-302.69, p=0.004). Infrastructure programs show positive but non-significant effects (HR=5.69, p=0.374). Housing programs show null effects (HR=0.82, p=0.891).\n\nThe mechanism is straightforward: construction activities face binding constraints---permitting, contractor availability, weather, beneficiary coordination---that velocity cannot overcome. Administration and planning activities face fewer external constraints; their pace depends primarily on organizational choices. Velocity interventions should therefore target administrative capacity-building rather than physical construction programs.\n\nThis finding has immediate policy implications. HUD's current monitoring emphasizes overall expenditure pace across all program types. A differentiated approach would apply intensive velocity monitoring to administration programs while allowing housing and infrastructure programs longer timelines consistent with construction realities.\n\n## Disaster Context Heterogeneity\n\n::: {#cell-fig-disaster-context .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![Velocity Effects by Disaster Type](index_files/figure-html/fig-disaster-context-output-1.png){#fig-disaster-context width=600}\n:::\n:::\n\n\nDisaster type produces the strongest heterogeneity. Wildfire disasters show extreme velocity effects (HR=51.09, 95% CI: 4.01-650.90, p=0.002)---the strongest effect in the entire analysis. Hurricane disasters show significant moderate effects (HR=4.58, 95% CI: 1.18-17.81, p=0.028). Other disaster types show positive but non-significant effects.\n\nThe wildfire result reflects time-constrained recovery. Wildfire-affected communities face seasonal fire risk that creates urgency to complete rebuilding before the next fire season. Slow recovery extends vulnerability. In contrast, hurricane and flood recovery, while urgent, allows more extended timelines without compounding risk.\n\nEra effects reinforce the time-constraint interpretation. The 2010-2020 period shows significant velocity effects (HR=5.36, p=0.010), corresponding to HUD's enhanced velocity monitoring and technical assistance during this period. Earlier and later eras show weaker effects, suggesting that policy emphasis on velocity moderates its relationship to completion.\n\n## Meta-Analytic Summary\n\n::: {#cell-fig-meta .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Meta-Analysis of All Velocity Effect Estimates](index_files/figure-html/fig-meta-output-1.png){#fig-meta width=700}\n:::\n:::\n\n\n::: {#tbl-meta-summary .cell tbl-cap='Summary of 16 Velocity Effect Estimates' execution_count=13}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Metric                 | Value        |\n|:-----------------------|:-------------|\n| Total estimates        | 16           |\n| Significant (p < 0.05) | 9 (56.2%)    |\n| HR > 1 (acceleration)  | 13 (81.2%)   |\n| Median HR              | 4.60         |\n| Mean HR                | 8.19         |\n| Range                  | 0.37 - 51.09 |\n| 25th-75th percentile   | 2.39 - 5.33  |\n:::\n:::\n\n\nMeta-analysis of 16 velocity effect estimates reveals substantial heterogeneity around a positive central tendency. The median hazard ratio is 4.60, indicating that across diverse contexts, higher velocity typically accelerates completion. However, the range from 0.37 to 51.09 demonstrates that velocity effects are far from universal.\n\nThe three strongest effects identify high-leverage intervention contexts: wildfire disasters (HR=51.09, p=0.002), where time-constrained recovery creates seasonal fire risk urgency; administration programs (HR=30.74, p=0.004), where organizational choices determine pace rather than external construction constraints; and late program phases (HR=5.00, p=0.040), where closeout bottlenecks create critical barriers. Null effects in housing programs, experienced grantees, and early phases identify contexts where velocity interventions are unlikely to yield returns.\n\n# Discussion\n\n## The Contingent Capacity Framework\n\nFindings support a contingent capacity framework where velocity effects depend on two interacting conditions: time constraints and capacity substitutability.\n\nTime constraints create urgency that magnifies velocity effects. Wildfire recovery must complete before the next fire season. Late-phase programs face political deadline pressure and compliance verification bottlenecks. Administration programs lack fixed construction timelines, making pace entirely dependent on organizational velocity. In these contexts, slow progress translates directly to delayed completion.\n\nCapacity substitutability moderates whether velocity is the relevant capacity dimension. Experienced grantees have accumulated institutional knowledge, vendor networks, and political capital that provide alternative completion pathways. When velocity slows, these resources can substitute. Novice grantees and administration programs lack substitutes; velocity is their primary capacity mechanism.\n\nThe interaction produces the observed pattern. Velocity effects are strongest when time constraints bind AND substitutes are absent (wildfire, administration, novice, late phase). Velocity effects are weakest when time constraints are loose OR substitutes are available (housing, experienced, early phase).\n\n## Mechanisms\n\nSeveral mechanisms explain velocity-completion associations within this framework.\n\nCloseout bottlenecks create late-phase urgency. Programs approaching completion face concentrated compliance verification, final reporting requirements, and fund reconciliation. Programs that maintain velocity through these bottlenecks complete; programs that slow accumulate delays that compound over time.\n\nMomentum effects link velocity to project continuity. Active programs maintain contractor relationships, staff expertise, and political attention. Velocity declines trigger contractor departures, staff reassignment, and diminished political priority---all of which create additional barriers to resumed progress.\n\nSeasonal constraints create natural deadlines in wildfire contexts. Rebuilding that extends past fire season exposes incomplete structures to destruction risk. This creates genuine time pressure that amplifies velocity effects relative to disasters without seasonal recurrence risk.\n\nInstitutional substitution explains experience moderation. Organizations with prior CDBG-DR experience have developed procurement templates, compliance knowledge, and federal relationships. These accumulated resources provide alternative completion mechanisms, reducing dependence on velocity as the sole capacity pathway.\n\n## Theoretical Contributions\n\n**Capacity effects are contingent, not universal.** Traditional capacity theory assumes that more capacity improves outcomes regardless of context. This analysis demonstrates that velocity effects range from null to extreme depending on task constraints and organizational alternatives. Public administration research should test boundary conditions rather than assuming universal effects.\n\n**Organizations pursue multiple pathways to completion.** Experienced grantees achieve completion through institutional knowledge, political capital, and vendor relationships---not just spending velocity. Configurational approaches that examine combinations of capacity dimensions better capture organizational effectiveness than single-indicator models.\n\n**Capacity effects vary across program lifecycle.** Late-phase velocity matters more than early-phase velocity, suggesting that capacity investments should be differentially timed. Front-loaded planning assistance and back-loaded closeout support are likely more effective than uniform monitoring.\n\n## Limitations\n\nSeveral limitations warrant consideration.\n\nSmall sample sizes in stratified analyses produce wide confidence intervals. The wildfire estimate (HR=51.09) has confidence bounds from 4.01 to 650.90, indicating substantial uncertainty about effect magnitude. Pooling data across disaster types or programs would increase precision at the cost of obscuring heterogeneity.\n\nCausality remains uncertain. High velocity may cause faster completion, or anticipated completion may cause high velocity as grantees accelerate toward finish lines. Time-varying Cox models with lagged velocity partially address this concern, but instrumental variable approaches would provide stronger causal identification.\n\nGeneralizability beyond CDBG-DR is unknown. CDBG-DR operates through existing Community Development Block Grant infrastructure with specific federal requirements. Findings may not extend to FEMA Public Assistance, SBA disaster loans, or international development programs with different institutional structures.\n\nMeasurement relies on financial velocity as the sole capacity indicator. Other capacity dimensions---staff expertise, political relationships, community engagement---may contribute to completion through pathways not captured by spending data. Multi-dimensional capacity measurement would provide a more complete picture.\n\n## Future Directions\n\nThree research directions would extend these findings.\n\nCase study validation could trace mechanisms in high- and low-velocity contexts. Comparative cases of wildfire programs that completed quickly versus slowly would test the time-constraint mechanism. Cases of novice versus experienced grantees facing similar disasters would test the substitution mechanism.\n\nIntervention trials would establish causal effects of velocity-enhancing interventions. Randomized or quasi-experimental assignment of intensive technical assistance to high-leverage contexts (wildfire, administration, novice) would test whether velocity improvements translate to faster completion.\n\nCross-program replication would assess generalizability. Applying identical methods to FEMA Public Assistance, non-disaster CDBG, or international development data would test whether context-dependent capacity effects extend beyond CDBG-DR.\n\n# Conclusion\n\nAdministrative capacity effects on disaster recovery completion are contingent, not universal. Spending velocity---the quarterly rate of fund expenditure---shows a median hazard ratio of 4.60 across 16 contexts, but effects range from null (housing programs, HR=0.82) to extreme (wildfire disasters, HR=51.09).\n\nThe contingent capacity framework identifies two conditions that concentrate velocity effects: binding time constraints and absent capacity substitutes. Wildfire disasters, administration programs, late program phases, and novice grantees exhibit the strongest velocity effects because they combine urgency with limited alternatives. Housing programs, experienced grantees, and early phases show weaker effects because they face looser constraints or have accumulated substitute resources.\n\nPolicy implications favor targeted over universal interventions. HUD technical assistance should concentrate on high-leverage contexts---wildfire recovery, administrative programs, closeout phases, first-time grantees---rather than applying uniform velocity monitoring across all disaster recovery programs. Differentiated monitoring would allocate 60% of assistance resources to contexts where velocity interventions yield substantial returns.\n\nThe theoretical implication challenges assumptions of universal capacity effects. Public administration research should identify boundary conditions and moderators rather than assuming that capacity investments yield uniform returns. Contingency theory, organizational learning, and configurational approaches offer frameworks for understanding when and why capacity matters.\n\nDisaster recovery remains among the most challenging domains of public administration. Programs routinely extend for decades while affected communities await reconstruction. Understanding what accelerates completion---and in which contexts---provides actionable guidance for policy design and program management. Velocity matters, but it matters most when time is short and alternatives are few.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}