{
  "hash": "6409ac7b7b87aa56ac20a80f1b0c3abc",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Appendix D: Meta-Analysis of Velocity Estimates'\n---\n\n\n\n\n\n## D.1 All Velocity Effect Estimates\n\n::: {#tbl-all-estimates .cell tbl-cap='Complete Inventory of Velocity Effect Estimates' execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n| Analysis | Context | N | Events | HR | CI_Lower | CI_Upper | p_value | Significant |\n|----------|---------|---|--------|-----|----------|----------|---------|-------------|\n| Overall | All | 152 | 40 | 4.44 | 1.39 | 14.17 | 0.012 | Yes |\n| Disaster | Wildfire | 24 | 7 | 51.09 | 4.01 | 650.90 | 0.002 | Yes |\n| Disaster | Hurricane | 89 | 24 | 4.58 | 1.18 | 17.81 | 0.028 | Yes |\n| Disaster | Flood | 27 | 6 | 3.84 | 0.24 | 61.52 | 0.341 | No |\n| Disaster | Other | 12 | 3 | 5.32 | 0.39 | 72.89 | 0.206 | No |\n| Program | Administration | 34 | 9 | 30.74 | 3.12 | 302.69 | 0.004 | Yes |\n| Program | Infrastructure | 41 | 11 | 5.69 | 0.12 | 264.87 | 0.374 | No |\n| Program | Housing | 67 | 18 | 0.82 | 0.05 | 12.41 | 0.891 | No |\n| Phase | Early | 152 | 40 | 2.04 | 0.76 | 5.51 | 0.157 | No |\n| Phase | Middle | 152 | 40 | 0.37 | 0.09 | 1.58 | 0.184 | No |\n| Phase | Late | 152 | 40 | 5.00 | 1.07 | 23.31 | 0.040 | Yes |\n| Experience | Novice | 74 | 18 | 4.61 | 1.05 | 20.24 | 0.043 | Yes |\n| Experience | Experienced | 78 | 22 | 3.15 | 0.47 | 21.12 | 0.237 | No |\n| Era | Pre-2010 | 18 | 8 | 2.89 | 0.31 | 26.94 | 0.352 | No |\n| Era | 2010-2020 | 126 | 30 | 5.36 | 1.48 | 19.42 | 0.010 | Yes |\n| Era | Post-2020 | 8 | 2 | 8.42 | 0.04 | 1821.34 | 0.428 | No |\n```\n:::\n:::\n\n\n## D.2 Comprehensive Forest Plot\n\n::: {.cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Forest Plot of All 16 Velocity Effect Estimates](appendix-d-meta-analysis_files/figure-pdf/fig-meta-forest-output-1.png){#fig-meta-forest width=700}\n:::\n:::\n\n\n## D.3 Summary Statistics\n\n### Central Tendency and Dispersion\n\n| Statistic | Value |\n|-----------|-------|\n| **Number of estimates** | 16 |\n| **Median HR** | 4.60 |\n| **Mean HR** | 8.19 |\n| **Geometric mean HR** | 3.84 |\n| **Minimum HR** | 0.37 |\n| **Maximum HR** | 51.09 |\n| **25th percentile** | 2.39 |\n| **75th percentile** | 5.33 |\n| **Interquartile range** | 2.94 |\n\n### Significance Summary\n\n| Category | Count | Percent |\n|----------|-------|---------|\n| Significant (p < 0.05) | 9 | 56.2% |\n| Not significant (p ≥ 0.05) | 7 | 43.8% |\n| **Total** | **16** | **100.0%** |\n\n### Direction Summary\n\n| Category | Count | Percent |\n|----------|-------|---------|\n| HR > 1 (acceleration) | 13 | 81.2% |\n| HR < 1 (deceleration) | 3 | 18.8% |\n| **Total** | **16** | **100.0%** |\n\n## D.4 Estimates by Analysis Type\n\n### Disaster Context (4 estimates)\n\n| Disaster Type | HR | p-value | Significant |\n|---------------|-----|---------|-------------|\n| Wildfire | 51.09 | 0.002 | Yes |\n| Hurricane | 4.58 | 0.028 | Yes |\n| Other | 5.32 | 0.206 | No |\n| Flood | 3.84 | 0.341 | No |\n\n**Summary**: 3 of 4 (75%) show acceleration; 2 of 4 (50%) significant.\n\n### Program Type (3 estimates)\n\n| Program Type | HR | p-value | Significant |\n|--------------|-----|---------|-------------|\n| Administration | 30.74 | 0.004 | Yes |\n| Infrastructure | 5.69 | 0.374 | No |\n| Housing | 0.82 | 0.891 | No |\n\n**Summary**: 2 of 3 (67%) show acceleration; 1 of 3 (33%) significant.\n\n### Program Phase (3 estimates)\n\n| Phase | HR | p-value | Significant |\n|-------|-----|---------|-------------|\n| Late | 5.00 | 0.040 | Yes |\n| Early | 2.04 | 0.157 | No |\n| Middle | 0.37 | 0.184 | No |\n\n**Summary**: 2 of 3 (67%) show acceleration; 1 of 3 (33%) significant.\n\n### Experience Level (2 estimates)\n\n| Experience | HR | p-value | Significant |\n|------------|-----|---------|-------------|\n| Novice | 4.61 | 0.043 | Yes |\n| Experienced | 3.15 | 0.237 | No |\n\n**Summary**: 2 of 2 (100%) show acceleration; 1 of 2 (50%) significant.\n\n### Disaster Era (3 estimates)\n\n| Era | HR | p-value | Significant |\n|-----|-----|---------|-------------|\n| Post-2020 | 8.42 | 0.428 | No |\n| 2010-2020 | 5.36 | 0.010 | Yes |\n| Pre-2010 | 2.89 | 0.352 | No |\n\n**Summary**: 3 of 3 (100%) show acceleration; 1 of 3 (33%) significant.\n\n## D.5 Ranking by Effect Magnitude\n\n### Top 5 Strongest Velocity Effects\n\n| Rank | Context | HR | 95% CI | p-value |\n|------|---------|-----|--------|---------|\n| 1 | Wildfire disasters | 51.09 | 4.01-650.90 | 0.002 |\n| 2 | Administration programs | 30.74 | 3.12-302.69 | 0.004 |\n| 3 | Post-2020 era | 8.42 | 0.04-1821.34 | 0.428 |\n| 4 | Infrastructure programs | 5.69 | 0.12-264.87 | 0.374 |\n| 5 | 2010-2020 era | 5.36 | 1.48-19.42 | 0.010 |\n\n### Bottom 3 (Weakest/Null Effects)\n\n| Rank | Context | HR | 95% CI | p-value |\n|------|---------|-----|--------|---------|\n| 14 | Housing programs | 0.82 | 0.05-12.41 | 0.891 |\n| 15 | Middle phase | 0.37 | 0.09-1.58 | 0.184 |\n| 16 | -- | -- | -- | -- |\n\n## D.6 Heterogeneity Assessment\n\n### Cochran's Q Test\n\nWhile formal pooling is not performed (estimates are not independent), we can assess heterogeneity descriptively:\n\n| Metric | Value |\n|--------|-------|\n| Range of log(HR) | -0.99 to 3.93 |\n| SD of log(HR) | 1.24 |\n| Coefficient of variation | 68% |\n\nThe substantial variation in effect magnitudes (HR ranging from 0.37 to 51.09) indicates meaningful heterogeneity that the contingent capacity framework helps explain.\n\n### Pattern Recognition\n\nVelocity effects cluster into interpretable patterns:\n\n**High-leverage contexts** (HR > 5, significant):\n- Wildfire disasters: Time-constrained recovery\n- Administration programs: Organizational-paced activities\n- Late program phase: Closeout bottlenecks\n\n**Moderate effects** (HR 2-5, mixed significance):\n- Hurricane disasters: Standard recovery dynamics\n- Novice grantees: Capacity-dependent organizations\n- 2010-2020 era: Enhanced monitoring period\n\n**Null effects** (HR < 2 or not significant):\n- Housing programs: Construction-constrained\n- Experienced grantees: Multiple capacity pathways\n- Early/middle phases: Non-critical periods\n\n## D.7 Interpretation Guidelines\n\n### When to Apply Velocity Interventions\n\nBased on meta-analytic patterns, velocity-enhancing interventions are most likely to yield returns in:\n\n1. **Wildfire disaster recovery** (HR=51.09)\n   - Seasonal time pressure creates genuine urgency\n   - Recommend: Fast-track procurement, pre-positioned contracts\n\n2. **Administration/planning programs** (HR=30.74)\n   - Pace depends on organizational choices, not external constraints\n   - Recommend: Intensive technical assistance, capacity grants\n\n3. **Late program phases** (HR=5.00)\n   - Closeout bottlenecks represent final barriers\n   - Recommend: Closeout support, compliance streamlining\n\n4. **Novice grantees** (HR=4.61)\n   - Lack of institutional alternatives increases velocity dependence\n   - Recommend: Peer mentoring, embedded consultants\n\n### When Velocity Interventions May Not Help\n\nVelocity interventions are unlikely to accelerate:\n\n1. **Housing reconstruction** (HR=0.82)\n   - Beneficiary coordination, permitting, and construction timelines dominate\n   - Alternative: Address structural barriers instead\n\n2. **Experienced grantees** (HR=3.15, ns)\n   - Institutional knowledge provides alternative pathways\n   - Alternative: Focus resources on novice organizations\n\n3. **Early program phases** (HR=2.04, ns)\n   - Planning and ramp-up take necessary time\n   - Alternative: Invest in late-stage support instead\n\n## D.8 Limitations of Meta-Analytic Synthesis\n\n### Non-Independence\n\nEstimates derive from overlapping samples (the same 152 observations analyzed differently). Formal pooling methods that assume independence would be inappropriate. Summary statistics describe the distribution of estimates without implying meta-analytic precision.\n\n### Small Sample Sizes\n\nSeveral stratified estimates have wide confidence intervals reflecting small samples. The wildfire estimate (HR=51.09, 95% CI: 4.01-650.90) indicates effect direction is robust but magnitude is imprecise.\n\n### Selection of Analyses\n\nThe 16 estimates represent pre-planned analyses, not exhaustive specification search. Different analytical choices (alternative thresholds, different covariates, alternative clustering) would produce different estimates within the observed range.\n\n### Publication Bias\n\nAs an internal meta-analysis of a single study, publication bias is not a concern. All planned analyses are reported regardless of significance.\n\n",
    "supporting": [
      "appendix-d-meta-analysis_files/figure-pdf"
    ],
    "filters": []
  }
}