"""
Provisional external reconstruction of Kaifa's later SEM workflow.

IMPORTANT
---------
This module is NOT Kaifa Lu's original notebook or script.
It is a repository-local reconstruction built from externally recovered
ready datasets and saved SEM exports that were imported into:

    manuscript_kaifa_archive/data/external_sem_exports/

Use this only as a temporary reproducibility layer until the original
analysis code is recovered. If the original notebook/scripts become
available, this module should be archived or replaced explicitly.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, UTC
import json
from pathlib import Path
import warnings

import pandas as pd

from config import DATA_WORK_DIR, PROJECT_ROOT

try:
    from semopy import Model, calc_stats
    SEMOPY_AVAILABLE = True
except ImportError:  # pragma: no cover - handled by callers/tests
    SEMOPY_AVAILABLE = False


KAIFA_EXTERNAL_LABEL = "PROVISIONAL_EXTERNAL_RECONSTRUCTION"
KAIFA_EXTERNAL_WARNING = (
    "This output was generated by a reconstructed workflow from imported "
    "external SEM exports. It is not Kaifa Lu's original analysis code."
)


@dataclass(frozen=True)
class ExternalSemBundle:
    """Locations for an imported external Kaifa SEM bundle."""

    name: str
    root: Path
    comparison_csv: Path
    one_factor_parameters_csv: Path
    two_factor_parameters_csv: Path
    ready_dataset_csv: Path
    two_factor_fit_csv: Path | None = None


EXTERNAL_SEM_ROOT = (
    PROJECT_ROOT / "manuscript_kaifa_archive" / "data" / "external_sem_exports"
)

EXTERNAL_SEM_BUNDLES = {
    "baseline_sem": ExternalSemBundle(
        name="baseline_sem",
        root=EXTERNAL_SEM_ROOT / "baseline_sem",
        comparison_csv=EXTERNAL_SEM_ROOT / "baseline_sem" / "sem_model_comparison.csv",
        one_factor_parameters_csv=(
            EXTERNAL_SEM_ROOT / "baseline_sem" / "baseline_sem_parameter_estimates.csv"
        ),
        two_factor_parameters_csv=(
            EXTERNAL_SEM_ROOT / "baseline_sem" / "sem_2factor_parameter_estimates.csv"
        ),
        ready_dataset_csv=(
            EXTERNAL_SEM_ROOT / "baseline_sem" / "sem_2factor_ready_dataset.csv"
        ),
        two_factor_fit_csv=(
            EXTERNAL_SEM_ROOT / "baseline_sem" / "sem_2factor_fit_statistics.csv"
        ),
    ),
    "baseline_sem_admin_4": ExternalSemBundle(
        name="baseline_sem_admin_4",
        root=EXTERNAL_SEM_ROOT / "baseline_sem_admin_4",
        comparison_csv=(
            EXTERNAL_SEM_ROOT / "baseline_sem_admin_4" / "sem_model_comparison.csv"
        ),
        one_factor_parameters_csv=(
            EXTERNAL_SEM_ROOT
            / "baseline_sem_admin_4"
            / "baseline_sem_parameter_estimates.csv"
        ),
        two_factor_parameters_csv=(
            EXTERNAL_SEM_ROOT
            / "baseline_sem_admin_4"
            / "sem_2factor_parameter_estimates.csv"
        ),
        ready_dataset_csv=(
            EXTERNAL_SEM_ROOT
            / "baseline_sem_admin_4"
            / "sem_2factor_ready_dataset.csv"
        ),
        two_factor_fit_csv=(
            EXTERNAL_SEM_ROOT
            / "baseline_sem_admin_4"
            / "sem_2factor_fit_statistics.csv"
        ),
    ),
}


ONE_FACTOR_MODEL_SPEC = """
# PROVISIONAL EXTERNAL RECONSTRUCTION
# Rebuilt from imported exports, not original Kaifa code.
GovCapacity =~ z_avg_employment + z_avg_payroll + z_rev_programs_per_staff + z_rev_disasters_per_staff
RecoveryPerformance =~ z_Ratio_disbursed_to_obligated + z_Ratio_expended_to_disbursed + z_Ratio_obligated_funds_fully_expended + z_Ratio_Program_Completed
RecoveryTimeliness =~ z_rev_Duration_of_completion + z_rev_Average_Duration_Program_Completion
RecoveryPerformance ~ GovCapacity + state_level + z_E_TOTPOP + z_SPL_THEME1 + z_SPL_THEME2 + z_SPL_THEME3 + z_SPL_THEME4
RecoveryTimeliness ~ GovCapacity + state_level + z_E_TOTPOP + z_SPL_THEME1 + z_SPL_THEME2 + z_SPL_THEME3 + z_SPL_THEME4
"""


TWO_FACTOR_MODEL_SPEC = """
# PROVISIONAL EXTERNAL RECONSTRUCTION
# Rebuilt from imported exports, not original Kaifa code.
AdminResources =~ z_avg_employment + z_avg_payroll
AdminBurdenCapacity =~ z_rev_programs_per_staff + z_rev_disasters_per_staff
RecoveryPerformance =~ z_Ratio_disbursed_to_obligated + z_Ratio_expended_to_disbursed + z_Ratio_obligated_funds_fully_expended + z_Ratio_Program_Completed
RecoveryTimeliness =~ z_rev_Duration_of_completion + z_rev_Average_Duration_Program_Completion
RecoveryPerformance ~ AdminResources + AdminBurdenCapacity + state_level + z_E_TOTPOP + z_SPL_THEME1 + z_SPL_THEME2 + z_SPL_THEME3 + z_SPL_THEME4
RecoveryTimeliness ~ AdminResources + AdminBurdenCapacity + state_level + z_E_TOTPOP + z_SPL_THEME1 + z_SPL_THEME2 + z_SPL_THEME3 + z_SPL_THEME4
"""


FIT_STATISTICS = [
    "DoF",
    "DoF Baseline",
    "chi2",
    "chi2 p-value",
    "chi2 Baseline",
    "CFI",
    "GFI",
    "AGFI",
    "NFI",
    "TLI",
    "RMSEA",
    "AIC",
    "BIC",
]


def resolve_external_bundle(bundle_name: str) -> ExternalSemBundle:
    """Return the imported bundle metadata."""
    if bundle_name not in EXTERNAL_SEM_BUNDLES:
        available = ", ".join(sorted(EXTERNAL_SEM_BUNDLES))
        raise ValueError(f"Unknown external SEM bundle: {bundle_name}. Available: {available}")
    return EXTERNAL_SEM_BUNDLES[bundle_name]


def load_external_bundle(bundle_name: str) -> dict[str, pd.DataFrame]:
    """Load ready data and exported SEM tables from an imported bundle."""
    bundle = resolve_external_bundle(bundle_name)

    comparison = pd.read_csv(bundle.comparison_csv).rename(columns={"Unnamed: 0": "Statistic"})
    one_factor_parameters = pd.read_csv(bundle.one_factor_parameters_csv)
    two_factor_parameters = pd.read_csv(bundle.two_factor_parameters_csv)
    ready_dataset = pd.read_csv(bundle.ready_dataset_csv)

    two_factor_fit = None
    if bundle.two_factor_fit_csv and bundle.two_factor_fit_csv.exists():
        two_factor_fit = pd.read_csv(bundle.two_factor_fit_csv).rename(
            columns={"Unnamed: 0": "Statistic"}
        )

    return {
        "comparison": comparison,
        "one_factor_parameters": one_factor_parameters,
        "two_factor_parameters": two_factor_parameters,
        "ready_dataset": ready_dataset,
        "two_factor_fit": two_factor_fit,
    }


def _fit_sem_model(model_spec: str, data: pd.DataFrame) -> tuple[Model, pd.DataFrame, pd.DataFrame]:
    """Fit a semopy model and return the model, parameters, and fit statistics."""
    if not SEMOPY_AVAILABLE:
        raise ImportError("semopy is required for external SEM reconstruction")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        model = Model(model_spec)
        model.fit(data)

    params = model.inspect(std_est=True)
    raw_stats = calc_stats(model)
    stats_row = raw_stats.loc["Value"] if "Value" in raw_stats.index else raw_stats.iloc[0]
    fit_stats = (
        stats_row.rename_axis("Statistic")
        .reset_index(name="Value")
    )
    return model, params, fit_stats


def build_fit_comparison(
    exported_comparison: pd.DataFrame,
    one_factor_fit: pd.DataFrame,
    two_factor_fit: pd.DataFrame,
) -> pd.DataFrame:
    """Compare reconstructed fit statistics with the imported export table."""
    exported = exported_comparison.copy()
    exported = exported[exported["Statistic"].isin(FIT_STATISTICS)]
    refit_one = one_factor_fit.rename(columns={"Value": "Refit_OneFactor"})
    refit_two = two_factor_fit.rename(columns={"Value": "Refit_TwoFactor"})

    merged = (
        exported
        .merge(refit_one, on="Statistic", how="left")
        .merge(refit_two, on="Statistic", how="left")
        .rename(
            columns={
                "OneFactor": "Exported_OneFactor",
                "TwoFactor": "Exported_TwoFactor",
            }
        )
    )

    for left, right, delta in [
        ("Exported_OneFactor", "Refit_OneFactor", "Delta_OneFactor"),
        ("Exported_TwoFactor", "Refit_TwoFactor", "Delta_TwoFactor"),
    ]:
        merged[left] = pd.to_numeric(merged[left], errors="coerce")
        merged[right] = pd.to_numeric(merged[right], errors="coerce")
        merged[delta] = merged[right] - merged[left]

    return merged


def build_parameter_comparison(
    exported_parameters: pd.DataFrame,
    refit_parameters: pd.DataFrame,
    exported_label: str,
    refit_label: str,
) -> pd.DataFrame:
    """Compare exported parameter estimates with reconstructed estimates."""
    exported = exported_parameters.copy()
    refit = refit_parameters.copy()

    key_cols = ["lval", "op", "rval"]
    exported_numeric = {
        "Estimate": f"{exported_label}_Estimate",
        "Est. Std": f"{exported_label}_Est_Std",
        "p-value": f"{exported_label}_p_value",
    }
    refit_numeric = {
        "Estimate": f"{refit_label}_Estimate",
        "Est. Std": f"{refit_label}_Est_Std",
        "p-value": f"{refit_label}_p_value",
    }

    exported = exported[key_cols + list(exported_numeric)].rename(columns=exported_numeric)
    refit = refit[key_cols + list(refit_numeric)].rename(columns=refit_numeric)

    merged = exported.merge(refit, on=key_cols, how="outer")
    merged[f"{refit_label}_minus_{exported_label}_Estimate"] = (
        pd.to_numeric(merged[f"{refit_label}_Estimate"], errors="coerce")
        - pd.to_numeric(merged[f"{exported_label}_Estimate"], errors="coerce")
    )
    merged[f"{refit_label}_minus_{exported_label}_Est_Std"] = (
        pd.to_numeric(merged[f"{refit_label}_Est_Std"], errors="coerce")
        - pd.to_numeric(merged[f"{exported_label}_Est_Std"], errors="coerce")
    )

    return merged.sort_values(key_cols).reset_index(drop=True)


def default_external_output_dir(bundle_name: str) -> Path:
    """Default location for generated external reconstruction outputs."""
    return DATA_WORK_DIR / "diagnostics" / "kaifa_external_replication" / bundle_name


def _write_manifest(
    output_dir: Path,
    bundle: ExternalSemBundle,
    dataset: pd.DataFrame,
    fit_comparison: pd.DataFrame,
) -> None:
    """Write a manifest that makes the provisional status explicit."""
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "label": KAIFA_EXTERNAL_LABEL,
        "warning": KAIFA_EXTERNAL_WARNING,
        "generated_at_utc": datetime.now(UTC).isoformat(),
        "bundle_name": bundle.name,
        "bundle_root": str(bundle.root),
        "source_ready_dataset": str(bundle.ready_dataset_csv),
        "source_model_comparison": str(bundle.comparison_csv),
        "source_one_factor_parameters": str(bundle.one_factor_parameters_csv),
        "source_two_factor_parameters": str(bundle.two_factor_parameters_csv),
        "n_rows": int(len(dataset)),
        "n_columns": int(dataset.shape[1]),
        "fit_deltas": {
            "one_factor_cfi_delta": _safe_scalar(
                fit_comparison, "CFI", "Delta_OneFactor"
            ),
            "two_factor_cfi_delta": _safe_scalar(
                fit_comparison, "CFI", "Delta_TwoFactor"
            ),
            "one_factor_rmsea_delta": _safe_scalar(
                fit_comparison, "RMSEA", "Delta_OneFactor"
            ),
            "two_factor_rmsea_delta": _safe_scalar(
                fit_comparison, "RMSEA", "Delta_TwoFactor"
            ),
        },
    }

    manifest_path = output_dir / "external_reconstruction_manifest.json"
    manifest_path.write_text(json.dumps(summary, indent=2) + "\n")

    readme = output_dir / "README.md"
    readme.write_text(
        "\n".join(
            [
                "# Kaifa External SEM Reconstruction",
                "",
                f"Label: `{KAIFA_EXTERNAL_LABEL}`",
                "",
                f"Warning: {KAIFA_EXTERNAL_WARNING}",
                "",
                "This directory was generated from imported external SEM exports and a",
                "best-effort semopy reconstruction. It is not the original Kaifa",
                "analysis notebook or script.",
                "",
                f"- Bundle: `{bundle.name}`",
                f"- Source ready dataset: `{bundle.ready_dataset_csv}`",
                f"- Source comparison table: `{bundle.comparison_csv}`",
                "",
                "Generated files use the `external_reconstruction_*` prefix on purpose",
                "so they are not mistaken for original manuscript outputs.",
                "",
            ]
        )
        + "\n"
    )


def _safe_scalar(df: pd.DataFrame, statistic: str, column: str) -> float | None:
    """Extract a scalar from a fit comparison table if present."""
    match = df.loc[df["Statistic"] == statistic, column]
    if match.empty or pd.isna(match.iloc[0]):
        return None
    return float(match.iloc[0])


def run_external_replication(
    bundle_name: str = "baseline_sem",
    output_dir: str | Path | None = None,
    write_outputs: bool = True,
) -> dict[str, object]:
    """
    Refit the reconstructed one- and two-factor models on an imported bundle.

    This produces a provisional external reconstruction artifact set that can
    be used for Kaifa manuscript audit work while the original analysis code
    remains unavailable.
    """
    bundle = resolve_external_bundle(bundle_name)
    loaded = load_external_bundle(bundle_name)
    dataset = loaded["ready_dataset"]

    _, one_factor_parameters, one_factor_fit = _fit_sem_model(
        ONE_FACTOR_MODEL_SPEC, dataset
    )
    _, two_factor_parameters, two_factor_fit = _fit_sem_model(
        TWO_FACTOR_MODEL_SPEC, dataset
    )

    fit_comparison = build_fit_comparison(
        loaded["comparison"],
        one_factor_fit,
        two_factor_fit,
    )
    one_factor_parameter_comparison = build_parameter_comparison(
        loaded["one_factor_parameters"],
        one_factor_parameters,
        exported_label="Exported",
        refit_label="Refit",
    )
    two_factor_parameter_comparison = build_parameter_comparison(
        loaded["two_factor_parameters"],
        two_factor_parameters,
        exported_label="Exported",
        refit_label="Refit",
    )

    output_path = Path(output_dir) if output_dir else default_external_output_dir(bundle_name)

    if write_outputs:
        output_path.mkdir(parents=True, exist_ok=True)
        one_factor_parameters.to_csv(
            output_path / "external_reconstruction_one_factor_parameter_estimates.csv",
            index=False,
        )
        two_factor_parameters.to_csv(
            output_path / "external_reconstruction_two_factor_parameter_estimates.csv",
            index=False,
        )
        one_factor_fit.to_csv(
            output_path / "external_reconstruction_one_factor_fit_statistics.csv",
            index=False,
        )
        two_factor_fit.to_csv(
            output_path / "external_reconstruction_two_factor_fit_statistics.csv",
            index=False,
        )
        fit_comparison.to_csv(
            output_path / "external_reconstruction_fit_comparison.csv",
            index=False,
        )
        one_factor_parameter_comparison.to_csv(
            output_path / "external_reconstruction_one_factor_parameter_comparison.csv",
            index=False,
        )
        two_factor_parameter_comparison.to_csv(
            output_path / "external_reconstruction_two_factor_parameter_comparison.csv",
            index=False,
        )
        _write_manifest(output_path, bundle, dataset, fit_comparison)

    return {
        "label": KAIFA_EXTERNAL_LABEL,
        "warning": KAIFA_EXTERNAL_WARNING,
        "bundle": bundle,
        "dataset": dataset,
        "one_factor_parameters": one_factor_parameters,
        "two_factor_parameters": two_factor_parameters,
        "one_factor_fit": one_factor_fit,
        "two_factor_fit": two_factor_fit,
        "fit_comparison": fit_comparison,
        "one_factor_parameter_comparison": one_factor_parameter_comparison,
        "two_factor_parameter_comparison": two_factor_parameter_comparison,
        "output_dir": output_path,
    }
